package com.fitlog.ui.screens.training.action

import com.fitlog.ui.muscle.MuscleRegion
import com.fitlog.ui.screens.training.TrainingTarget

// AUTO-GENERATED from docs/exercise-library-seed/EXERCISE_LIBRARY_SEED.csv (82 actions).
object SampleExercises {
    val all: List<ExerciseOption> = listOf(
        ExerciseOption(
            id = 1, name = "杠铃卧推", mainPart = TrainingTarget.CHEST,
            intro = "仰卧在卧推凳上，双脚踩稳，肩胛骨向后下方收紧。", equipment = "杠铃",
            steps = listOf("仰卧在卧推凳上，双脚踩稳，肩胛骨向后下方收紧。", "握距略宽于肩，控制杠铃下降至胸部附近后向上推起。", "全程保持手腕中立，推起时不要耸肩或过度锁死手肘。"),
            cautions = listOf("不要让杠铃弹胸。", "大重量时建议使用保护架或同伴保护。", "腰背可自然反弓，但臀部不要离开凳面。"),
            primaryMuscles = listOf(MuscleRegion.CHEST),
            secondaryMuscles = listOf(MuscleRegion.DELTOIDS, MuscleRegion.TRICEPS),
            recordingType = RecordingType.STRENGTH,
        ),
        ExerciseOption(
            id = 2, name = "哑铃卧推", mainPart = TrainingTarget.CHEST,
            intro = "仰卧持哑铃，手腕稳定，哑铃位于胸部两侧上方。", equipment = "哑铃",
            steps = listOf("仰卧持哑铃，手腕稳定，哑铃位于胸部两侧上方。", "控制哑铃向下打开至胸部两侧，再沿弧线推回上方。", "顶端可略向内收，但不要让哑铃互相猛烈碰撞。"),
            cautions = listOf("避免哑铃下降过深造成肩前侧不适。", "保持两侧动作同步。", "选择能稳定控制的重量。"),
            primaryMuscles = listOf(MuscleRegion.CHEST),
            secondaryMuscles = listOf(MuscleRegion.DELTOIDS, MuscleRegion.TRICEPS),
            recordingType = RecordingType.STRENGTH,
        ),
        ExerciseOption(
            id = 3, name = "上斜哑铃卧推", mainPart = TrainingTarget.CHEST,
            intro = "将凳背调至约30-45度，肩胛稳定贴住靠背。", equipment = "哑铃",
            steps = listOf("将凳背调至约30-45度，肩胛稳定贴住靠背。", "哑铃从上胸两侧下降，再向上推至肩上方。", "保持肘部略低于肩线，感受上胸发力。"),
            cautions = listOf("凳角过高会更多刺激肩部。", "不要耸肩顶起重量。", "下放速度要可控。"),
            primaryMuscles = listOf(MuscleRegion.CHEST),
            secondaryMuscles = listOf(MuscleRegion.DELTOIDS, MuscleRegion.TRICEPS),
            recordingType = RecordingType.STRENGTH,
        ),
        ExerciseOption(
            id = 4, name = "上斜杠铃卧推", mainPart = TrainingTarget.CHEST,
            intro = "躺在上斜凳上，握距略宽于肩，肩胛后收。", equipment = "杠铃",
            steps = listOf("躺在上斜凳上，握距略宽于肩，肩胛后收。", "杠铃下降至上胸附近后平稳推起。", "保持前臂接近垂直，避免杠铃路径过度前后晃动。"),
            cautions = listOf("不要让杠铃砸向锁骨。", "肩部不适时降低角度或换哑铃。", "大重量使用保护。"),
            primaryMuscles = listOf(MuscleRegion.CHEST),
            secondaryMuscles = listOf(MuscleRegion.DELTOIDS, MuscleRegion.TRICEPS),
            recordingType = RecordingType.STRENGTH,
        ),
        ExerciseOption(
            id = 5, name = "俯卧撑", mainPart = TrainingTarget.CHEST,
            intro = "双手略宽于肩，身体从头到脚保持一条直线。", equipment = "自重",
            steps = listOf("双手略宽于肩，身体从头到脚保持一条直线。", "弯肘下降至胸部接近地面，再推回起始位置。", "收紧腹部和臀部，避免塌腰或抬臀。"),
            cautions = listOf("手腕不适可用俯卧撑支架。", "不要耸肩。", "动作幅度以肩部舒适为前提。"),
            primaryMuscles = listOf(MuscleRegion.CHEST),
            secondaryMuscles = listOf(MuscleRegion.DELTOIDS, MuscleRegion.TRICEPS, MuscleRegion.ABS),
            recordingType = RecordingType.BODYWEIGHT,
        ),
        ExerciseOption(
            id = 6, name = "双杠臂屈伸（胸向）", mainPart = TrainingTarget.CHEST,
            intro = "双手支撑双杠，身体略前倾，肩胛稳定。", equipment = "双杠",
            steps = listOf("双手支撑双杠，身体略前倾，肩胛稳定。", "弯肘下降至胸部有拉伸感，再推起身体。", "保持前倾可增强胸部参与，肘部自然向后外侧打开。"),
            cautions = listOf("肩前侧不适时减少下放幅度。", "不要在底部突然反弹。", "初学者可用辅助器械。"),
            primaryMuscles = listOf(MuscleRegion.CHEST),
            secondaryMuscles = listOf(MuscleRegion.TRICEPS, MuscleRegion.DELTOIDS),
            recordingType = RecordingType.STRENGTH,
        ),
        ExerciseOption(
            id = 7, name = "绳索夹胸", mainPart = TrainingTarget.CHEST,
            intro = "站在龙门架中间，双手握把，身体略前倾。", equipment = "龙门架",
            steps = listOf("站在龙门架中间，双手握把，身体略前倾。", "手臂微屈，从两侧向胸前合拢。", "顶点主动挤压胸肌，回放时保持控制。"),
            cautions = listOf("不要用身体摆动借力。", "肘角保持相对固定。", "避免肩膀向前耸起。"),
            primaryMuscles = listOf(MuscleRegion.CHEST),
            secondaryMuscles = listOf(MuscleRegion.DELTOIDS),
            recordingType = RecordingType.STRENGTH,
        ),
        ExerciseOption(
            id = 8, name = "蝴蝶机夹胸", mainPart = TrainingTarget.CHEST,
            intro = "调整座椅高度，使手柄与胸部大致同高。", equipment = "器械",
            steps = listOf("调整座椅高度，使手柄与胸部大致同高。", "前臂或双手推动手柄向中间合拢。", "缓慢回放，保持胸部持续受力。"),
            cautions = listOf("不要让重量片猛撞。", "肩部不适时减少后展幅度。", "背部贴靠垫，不要前探。"),
            primaryMuscles = listOf(MuscleRegion.CHEST),
            secondaryMuscles = listOf(MuscleRegion.DELTOIDS),
            recordingType = RecordingType.STRENGTH,
        ),
        ExerciseOption(
            id = 9, name = "坐姿推胸器", mainPart = TrainingTarget.CHEST,
            intro = "调整座椅，让手柄与胸部中线接近。", equipment = "器械",
            steps = listOf("调整座椅，让手柄与胸部中线接近。", "背部贴紧靠垫，向前推至手臂接近伸直。", "回放时控制速度，保持胸部张力。"),
            cautions = listOf("不要耸肩顶手柄。", "避免肘部完全锁死。", "重量过大时容易用肩代偿。"),
            primaryMuscles = listOf(MuscleRegion.CHEST),
            secondaryMuscles = listOf(MuscleRegion.DELTOIDS, MuscleRegion.TRICEPS),
            recordingType = RecordingType.STRENGTH,
        ),
        ExerciseOption(
            id = 10, name = "哑铃飞鸟", mainPart = TrainingTarget.CHEST,
            intro = "仰卧持哑铃，双臂在胸上方微屈。", equipment = "哑铃",
            steps = listOf("仰卧持哑铃，双臂在胸上方微屈。", "沿弧线打开双臂至胸部拉伸，再夹回上方。", "肘部角度保持稳定，重点感受胸部拉伸和夹紧。"),
            cautions = listOf("不要用过重哑铃。", "肩前侧不适时缩小幅度。", "避免肘部伸直做成肩关节硬拉。"),
            primaryMuscles = listOf(MuscleRegion.CHEST),
            secondaryMuscles = listOf(MuscleRegion.DELTOIDS),
            recordingType = RecordingType.STRENGTH,
        ),
        ExerciseOption(
            id = 11, name = "引体向上", mainPart = TrainingTarget.BACK,
            intro = "双手正握单杠，身体自然悬垂，肩胛先下沉。", equipment = "自重",
            steps = listOf("双手正握单杠，身体自然悬垂，肩胛先下沉。", "用背部带动身体向上，直到下巴接近或超过杠。", "下降时控制速度，保持肩胛稳定。"),
            cautions = listOf("不要只用手臂硬拉。", "避免摆腿借力。", "肩部不适时可改高位下拉。"),
            primaryMuscles = listOf(MuscleRegion.UPPER_BACK),
            secondaryMuscles = listOf(MuscleRegion.BICEPS, MuscleRegion.TRAPEZIUS, MuscleRegion.UPPER_BACK),
            recordingType = RecordingType.BODYWEIGHT,
        ),
        ExerciseOption(
            id = 12, name = "反握引体向上", mainPart = TrainingTarget.BACK,
            intro = "双手反握单杠，握距约肩宽。", equipment = "自重",
            steps = listOf("双手反握单杠，握距约肩宽。", "收紧核心，向上拉至胸部接近杠。", "下降到手臂伸展但肩不松垮。"),
            cautions = listOf("不要耸肩。", "避免身体大幅摆动。", "肘腕不适时调整握距。"),
            primaryMuscles = listOf(MuscleRegion.UPPER_BACK),
            secondaryMuscles = listOf(MuscleRegion.BICEPS, MuscleRegion.FOREARM),
            recordingType = RecordingType.BODYWEIGHT,
        ),
        ExerciseOption(
            id = 13, name = "高位下拉", mainPart = TrainingTarget.BACK,
            intro = "坐稳并固定大腿，双手握住拉杆。", equipment = "高位下拉器",
            steps = listOf("坐稳并固定大腿，双手握住拉杆。", "先下沉肩胛，再将拉杆拉向上胸。", "慢速还原，感受背阔肌被拉长。"),
            cautions = listOf("不要把拉杆拉到颈后。", "避免身体后仰过大。", "不要用手臂抢发力。"),
            primaryMuscles = listOf(MuscleRegion.UPPER_BACK),
            secondaryMuscles = listOf(MuscleRegion.BICEPS, MuscleRegion.TRAPEZIUS),
            recordingType = RecordingType.STRENGTH,
        ),
        ExerciseOption(
            id = 14, name = "坐姿绳索划船", mainPart = TrainingTarget.BACK,
            intro = "坐稳，脚踩踏板，背部保持中立。", equipment = "绳索划船机",
            steps = listOf("坐稳，脚踩踏板，背部保持中立。", "拉手柄至腹部附近，同时肩胛向后收。", "缓慢前送手柄，保持躯干稳定。"),
            cautions = listOf("不要用腰部大幅前后摆动。", "肩膀不要耸起。", "拉到末端时不要过度挺腰。"),
            primaryMuscles = listOf(MuscleRegion.UPPER_BACK),
            secondaryMuscles = listOf(MuscleRegion.BICEPS, MuscleRegion.TRAPEZIUS),
            recordingType = RecordingType.STRENGTH,
        ),
        ExerciseOption(
            id = 15, name = "杠铃俯身划船", mainPart = TrainingTarget.BACK,
            intro = "髋部后坐，躯干前倾，背部保持中立。", equipment = "杠铃",
            steps = listOf("髋部后坐，躯干前倾，背部保持中立。", "将杠铃拉向下腹或肚脐附近。", "下放时保持肩胛控制，不让背部塌陷。"),
            cautions = listOf("不要圆背拉重量。", "避免用髋部猛甩借力。", "腰部疲劳时降低重量或改支撑划船。"),
            primaryMuscles = listOf(MuscleRegion.UPPER_BACK),
            secondaryMuscles = listOf(MuscleRegion.BICEPS, MuscleRegion.LOWER_BACK, MuscleRegion.TRAPEZIUS),
            recordingType = RecordingType.STRENGTH,
        ),
        ExerciseOption(
            id = 16, name = "单臂哑铃划船", mainPart = TrainingTarget.BACK,
            intro = "一手一膝支撑在凳上，背部保持平直。", equipment = "哑铃",
            steps = listOf("一手一膝支撑在凳上，背部保持平直。", "将哑铃沿身体侧面拉向髋部。", "顶部肩胛向后下方收，慢速下放。"),
            cautions = listOf("不要扭转躯干借力。", "避免耸肩。", "左右重量和次数保持一致。"),
            primaryMuscles = listOf(MuscleRegion.UPPER_BACK),
            secondaryMuscles = listOf(MuscleRegion.BICEPS, MuscleRegion.UPPER_BACK, MuscleRegion.DELTOIDS),
            recordingType = RecordingType.STRENGTH,
        ),
        ExerciseOption(
            id = 17, name = "胸托划船", mainPart = TrainingTarget.BACK,
            intro = "胸部贴住靠垫或上斜凳，双手持握把或哑铃。", equipment = "器械",
            steps = listOf("胸部贴住靠垫或上斜凳，双手持握把或哑铃。", "向后拉至肘部超过躯干，肩胛收紧。", "下放时保持胸部贴垫，减少腰部代偿。"),
            cautions = listOf("不要抬胸离开靠垫。", "避免耸肩。", "肘部路径根据目标背部区域微调。"),
            primaryMuscles = listOf(MuscleRegion.UPPER_BACK),
            secondaryMuscles = listOf(MuscleRegion.BICEPS, MuscleRegion.DELTOIDS),
            recordingType = RecordingType.STRENGTH,
        ),
        ExerciseOption(
            id = 18, name = "T杠划船", mainPart = TrainingTarget.BACK,
            intro = "双脚站稳，髋部后坐，握住T杠把手。", equipment = "T杠",
            steps = listOf("双脚站稳，髋部后坐，握住T杠把手。", "将把手拉向胸腹部，肩胛主动后收。", "下放到手臂伸展但背部不松散。"),
            cautions = listOf("不要圆背。", "重量过大时容易耸肩或甩动。", "腰部不适时换胸托版本。"),
            primaryMuscles = listOf(MuscleRegion.UPPER_BACK),
            secondaryMuscles = listOf(MuscleRegion.BICEPS, MuscleRegion.TRAPEZIUS, MuscleRegion.LOWER_BACK),
            recordingType = RecordingType.STRENGTH,
        ),
        ExerciseOption(
            id = 19, name = "直臂下拉", mainPart = TrainingTarget.BACK,
            intro = "站在高位绳索前，双臂微屈握杆。", equipment = "绳索",
            steps = listOf("站在高位绳索前，双臂微屈握杆。", "保持肘角稳定，将杆向大腿方向下压。", "慢慢回到头顶前方，感受背阔肌拉伸。"),
            cautions = listOf("不要屈肘做成下压。", "避免身体前后摆动。", "肩部不适时缩小幅度。"),
            primaryMuscles = listOf(MuscleRegion.UPPER_BACK),
            secondaryMuscles = listOf(MuscleRegion.UPPER_BACK, MuscleRegion.ABS),
            recordingType = RecordingType.STRENGTH,
        ),
        ExerciseOption(
            id = 20, name = "面拉", mainPart = TrainingTarget.SHOULDER,
            intro = "将绳索调到面部高度，双手握绳。", equipment = "绳索",
            steps = listOf("将绳索调到面部高度，双手握绳。", "向脸部拉绳，肘部向外打开，肩胛后收。", "末端轻微外旋，慢速还原。"),
            cautions = listOf("不要用下背后仰借力。", "避免耸肩。", "重量宁轻不重，重视控制。"),
            primaryMuscles = listOf(MuscleRegion.DELTOIDS),
            secondaryMuscles = listOf(MuscleRegion.TRAPEZIUS),
            recordingType = RecordingType.STRENGTH,
        ),
        ExerciseOption(
            id = 21, name = "硬拉", mainPart = TrainingTarget.BACK,
            intro = "站在杠铃中间，髋部后坐，背部保持中立。", equipment = "杠铃",
            steps = listOf("站在杠铃中间，髋部后坐，背部保持中立。", "用腿和髋同时发力，将杠铃贴近身体拉起。", "顶端站直但不要过度后仰。"),
            cautions = listOf("不要圆背起拉。", "杠铃远离身体会增加腰部压力。", "大重量前充分热身。"),
            primaryMuscles = listOf(MuscleRegion.GLUTES, MuscleRegion.HAMSTRINGS, MuscleRegion.LOWER_BACK),
            secondaryMuscles = listOf(MuscleRegion.UPPER_BACK, MuscleRegion.TRAPEZIUS, MuscleRegion.FOREARM, MuscleRegion.ABS),
            recordingType = RecordingType.STRENGTH,
        ),
        ExerciseOption(
            id = 22, name = "杠铃推举", mainPart = TrainingTarget.SHOULDER,
            intro = "杠铃置于锁骨上方，双脚站稳，核心收紧。", equipment = "杠铃",
            steps = listOf("杠铃置于锁骨上方，双脚站稳，核心收紧。", "沿接近垂直路径将杠铃推过头顶。", "头部让开杠铃路径，顶端身体回到杠下。"),
            cautions = listOf("不要过度后仰。", "手腕保持中立。", "肩部不适时改哑铃或器械。"),
            primaryMuscles = listOf(MuscleRegion.DELTOIDS),
            secondaryMuscles = listOf(MuscleRegion.TRICEPS, MuscleRegion.CHEST, MuscleRegion.ABS),
            recordingType = RecordingType.STRENGTH,
        ),
        ExerciseOption(
            id = 23, name = "哑铃肩推", mainPart = TrainingTarget.SHOULDER,
            intro = "坐姿或站姿持哑铃于肩两侧。", equipment = "哑铃",
            steps = listOf("坐姿或站姿持哑铃于肩两侧。", "向上推至手臂接近伸直，再控制回到肩部高度。", "保持肘部略在身体前侧，减少肩夹挤。"),
            cautions = listOf("不要耸肩。", "避免腰部过度反弓。", "两侧动作保持对称。"),
            primaryMuscles = listOf(MuscleRegion.DELTOIDS),
            secondaryMuscles = listOf(MuscleRegion.TRICEPS, MuscleRegion.CHEST),
            recordingType = RecordingType.STRENGTH,
        ),
        ExerciseOption(
            id = 24, name = "阿诺德推举", mainPart = TrainingTarget.SHOULDER,
            intro = "哑铃从胸前开始，掌心朝向自己。", equipment = "哑铃",
            steps = listOf("哑铃从胸前开始，掌心朝向自己。", "推起过程中旋转手臂，顶端掌心朝前。", "下放按相反路径控制回到起始位置。"),
            cautions = listOf("动作不适合过重重量。", "不要用腰部摆动。", "肩部活动受限者谨慎。"),
            primaryMuscles = listOf(MuscleRegion.DELTOIDS),
            secondaryMuscles = listOf(MuscleRegion.TRICEPS, MuscleRegion.CHEST),
            recordingType = RecordingType.STRENGTH,
        ),
        ExerciseOption(
            id = 25, name = "哑铃侧平举", mainPart = TrainingTarget.SHOULDER,
            intro = "双手持哑铃站立，肘部微屈。", equipment = "哑铃",
            steps = listOf("双手持哑铃站立，肘部微屈。", "将哑铃向身体两侧抬至肩高附近。", "下放时控制速度，保持三角肌张力。"),
            cautions = listOf("不要耸肩抢力。", "不要甩动借力。", "手腕不要高于肘太多。"),
            primaryMuscles = listOf(MuscleRegion.DELTOIDS),
            secondaryMuscles = listOf(MuscleRegion.TRAPEZIUS),
            recordingType = RecordingType.STRENGTH,
        ),
        ExerciseOption(
            id = 26, name = "绳索侧平举", mainPart = TrainingTarget.SHOULDER,
            intro = "站在低位绳索旁，远侧手握把。", equipment = "绳索",
            steps = listOf("站在低位绳索旁，远侧手握把。", "手臂从身体前侧或侧方抬起至肩高。", "绳索提供持续张力，慢速回放。"),
            cautions = listOf("不要耸肩。", "重量过大会破坏轨迹。", "保持躯干稳定。"),
            primaryMuscles = listOf(MuscleRegion.DELTOIDS),
            secondaryMuscles = listOf(MuscleRegion.TRAPEZIUS),
            recordingType = RecordingType.STRENGTH,
        ),
        ExerciseOption(
            id = 27, name = "前平举", mainPart = TrainingTarget.SHOULDER,
            intro = "双手持哑铃或杠铃片置于身体前方。", equipment = "哑铃",
            steps = listOf("双手持哑铃或杠铃片置于身体前方。", "将重量抬至肩高附近。", "慢速下放，不要让重量自由下坠。"),
            cautions = listOf("不要借腰部后仰。", "肩前侧不适时减少幅度。", "卧推量大的人不必过量添加。"),
            primaryMuscles = listOf(MuscleRegion.DELTOIDS),
            secondaryMuscles = listOf(MuscleRegion.CHEST, MuscleRegion.TRAPEZIUS),
            recordingType = RecordingType.STRENGTH,
        ),
        ExerciseOption(
            id = 28, name = "俯身反向飞鸟", mainPart = TrainingTarget.SHOULDER,
            intro = "髋部后坐俯身，背部保持中立。", equipment = "哑铃",
            steps = listOf("髋部后坐俯身，背部保持中立。", "双臂微屈向两侧打开，感受肩后侧发力。", "顶端短暂停顿后慢速下放。"),
            cautions = listOf("不要耸肩。", "不要用背部猛甩。", "重量宜轻，控制轨迹。"),
            primaryMuscles = listOf(MuscleRegion.DELTOIDS),
            secondaryMuscles = listOf(MuscleRegion.UPPER_BACK, MuscleRegion.TRAPEZIUS),
            recordingType = RecordingType.STRENGTH,
        ),
        ExerciseOption(
            id = 29, name = "直立划船", mainPart = TrainingTarget.SHOULDER,
            intro = "站立握杆或哑铃，手在身体前方。", equipment = "杠铃",
            steps = listOf("站立握杆或哑铃，手在身体前方。", "肘部带动重量向上拉至胸上部附近。", "保持重量靠近身体，慢速下放。"),
            cautions = listOf("肩夹挤不适者避免或缩小幅度。", "不要把肘部拉得过高。", "优先用绳索或哑铃获得更舒适路径。"),
            primaryMuscles = listOf(MuscleRegion.DELTOIDS),
            secondaryMuscles = listOf(MuscleRegion.TRAPEZIUS, MuscleRegion.BICEPS),
            recordingType = RecordingType.STRENGTH,
        ),
        ExerciseOption(
            id = 30, name = "耸肩", mainPart = TrainingTarget.SHOULDER,
            intro = "双手持重站立，手臂自然下垂。", equipment = "哑铃",
            steps = listOf("双手持重站立，手臂自然下垂。", "肩膀垂直向上耸起，顶端短暂停顿。", "慢速下降，保持颈部放松。"),
            cautions = listOf("不要转肩画圈。", "不要用腿蹬借力。", "颈部不适者减少重量。"),
            primaryMuscles = listOf(MuscleRegion.TRAPEZIUS),
            secondaryMuscles = listOf(MuscleRegion.FOREARM),
            recordingType = RecordingType.STRENGTH,
        ),
        ExerciseOption(
            id = 31, name = "杠铃弯举", mainPart = TrainingTarget.ARM,
            intro = "双手反握杠铃，肘部贴近身体两侧。", equipment = "杠铃",
            steps = listOf("双手反握杠铃，肘部贴近身体两侧。", "弯曲肘部将杠铃举至胸前，再控制下放。", "保持上臂稳定，感受肱二头肌收缩。"),
            cautions = listOf("不要身体后仰甩起。", "手腕不要过度弯折。", "重量过大时容易借力。"),
            primaryMuscles = listOf(MuscleRegion.BICEPS),
            secondaryMuscles = listOf(MuscleRegion.FOREARM, MuscleRegion.BICEPS),
            recordingType = RecordingType.STRENGTH,
        ),
        ExerciseOption(
            id = 32, name = "哑铃弯举", mainPart = TrainingTarget.ARM,
            intro = "双手持哑铃站立或坐姿，手臂自然下垂。", equipment = "哑铃",
            steps = listOf("双手持哑铃站立或坐姿，手臂自然下垂。", "弯举时可逐渐旋后手掌，顶端挤压肱二头肌。", "下放到手臂伸展但不松垮。"),
            cautions = listOf("不要耸肩。", "不要摆动躯干。", "左右动作保持一致。"),
            primaryMuscles = listOf(MuscleRegion.BICEPS),
            secondaryMuscles = listOf(MuscleRegion.FOREARM, MuscleRegion.BICEPS),
            recordingType = RecordingType.STRENGTH,
        ),
        ExerciseOption(
            id = 33, name = "锤式弯举", mainPart = TrainingTarget.ARM,
            intro = "双手中立握哑铃，掌心相对。", equipment = "哑铃",
            steps = listOf("双手中立握哑铃，掌心相对。", "保持上臂稳定，将哑铃向肩部弯举。", "慢速下放，保持前臂控制。"),
            cautions = listOf("不要借腰摆动。", "手腕保持中立。", "肘部不要向前跑太多。"),
            primaryMuscles = listOf(MuscleRegion.BICEPS, MuscleRegion.FOREARM),
            secondaryMuscles = listOf(MuscleRegion.BICEPS, MuscleRegion.FOREARM),
            recordingType = RecordingType.STRENGTH,
        ),
        ExerciseOption(
            id = 34, name = "牧师凳弯举", mainPart = TrainingTarget.ARM,
            intro = "上臂贴住牧师凳垫，握住杠铃或哑铃。", equipment = "牧师凳",
            steps = listOf("上臂贴住牧师凳垫，握住杠铃或哑铃。", "从接近伸展位置弯举到顶端。", "下放要慢，保持肘部稳定。"),
            cautions = listOf("不要在底部完全放松反弹。", "重量过重会牵拉肘部。", "保持肩部稳定。"),
            primaryMuscles = listOf(MuscleRegion.BICEPS),
            secondaryMuscles = listOf(MuscleRegion.BICEPS, MuscleRegion.FOREARM),
            recordingType = RecordingType.STRENGTH,
        ),
        ExerciseOption(
            id = 35, name = "绳索弯举", mainPart = TrainingTarget.ARM,
            intro = "站在低位绳索前，双手握直杆或绳。", equipment = "绳索",
            steps = listOf("站在低位绳索前，双手握直杆或绳。", "肘部固定，将把手向上弯举。", "慢速下放，利用绳索保持持续张力。"),
            cautions = listOf("不要身体后仰。", "肘部不要前后晃动。", "顶端不要耸肩。"),
            primaryMuscles = listOf(MuscleRegion.BICEPS),
            secondaryMuscles = listOf(MuscleRegion.FOREARM, MuscleRegion.BICEPS),
            recordingType = RecordingType.STRENGTH,
        ),
        ExerciseOption(
            id = 36, name = "窄握卧推", mainPart = TrainingTarget.ARM,
            intro = "仰卧握杠，握距略窄于普通卧推。", equipment = "杠铃",
            steps = listOf("仰卧握杠，握距略窄于普通卧推。", "控制杠铃下降至下胸附近，再推起。", "肘部保持相对靠近身体，强调三头发力。"),
            cautions = listOf("握距不要过窄以免手腕不适。", "不要肘部外翻过大。", "大重量使用保护。"),
            primaryMuscles = listOf(MuscleRegion.TRICEPS),
            secondaryMuscles = listOf(MuscleRegion.CHEST, MuscleRegion.DELTOIDS),
            recordingType = RecordingType.STRENGTH,
        ),
        ExerciseOption(
            id = 37, name = "绳索下压", mainPart = TrainingTarget.ARM,
            intro = "站在高位绳索前，肘部夹在身体两侧。", equipment = "绳索",
            steps = listOf("站在高位绳索前，肘部夹在身体两侧。", "向下伸直肘部，将把手压至大腿前。", "顶端挤压三头，慢速回到肘部约90度。"),
            cautions = listOf("不要耸肩压身体。", "上臂不要前后摆动。", "重量过大时容易借力。"),
            primaryMuscles = listOf(MuscleRegion.TRICEPS),
            secondaryMuscles = listOf(MuscleRegion.FOREARM),
            recordingType = RecordingType.STRENGTH,
        ),
        ExerciseOption(
            id = 38, name = "过顶臂屈伸", mainPart = TrainingTarget.ARM,
            intro = "双手持哑铃或绳索于头顶后方。", equipment = "哑铃",
            steps = listOf("双手持哑铃或绳索于头顶后方。", "保持上臂接近垂直，伸直肘部将重量推起。", "下放时感受三头长头拉伸。"),
            cautions = listOf("不要腰部过度反弓。", "肘部不要大幅外张。", "肩部不适时减少幅度。"),
            primaryMuscles = listOf(MuscleRegion.TRICEPS),
            secondaryMuscles = listOf(MuscleRegion.ABS, MuscleRegion.DELTOIDS),
            recordingType = RecordingType.STRENGTH,
        ),
        ExerciseOption(
            id = 39, name = "仰卧臂屈伸", mainPart = TrainingTarget.ARM,
            intro = "仰卧持杠或哑铃，手臂在胸上方。", equipment = "EZ杠",
            steps = listOf("仰卧持杠或哑铃，手臂在胸上方。", "弯肘将重量下降至额头或头后，再伸肘推回。", "上臂保持稳定，控制下放速度。"),
            cautions = listOf("不要让重量砸向头部。", "肘部不适时改绳索。", "避免过度外张肘部。"),
            primaryMuscles = listOf(MuscleRegion.TRICEPS),
            secondaryMuscles = listOf(MuscleRegion.FOREARM, MuscleRegion.DELTOIDS),
            recordingType = RecordingType.STRENGTH,
        ),
        ExerciseOption(
            id = 40, name = "凳上臂屈伸", mainPart = TrainingTarget.ARM,
            intro = "双手撑在凳沿，双脚向前放置。", equipment = "凳",
            steps = listOf("双手撑在凳沿，双脚向前放置。", "弯肘让身体下降，再用三头推回。", "保持身体靠近凳子，肩胛稳定。"),
            cautions = listOf("肩前侧不适者谨慎。", "不要下降过深。", "避免耸肩。"),
            primaryMuscles = listOf(MuscleRegion.TRICEPS),
            secondaryMuscles = listOf(MuscleRegion.CHEST, MuscleRegion.DELTOIDS),
            recordingType = RecordingType.STRENGTH,
        ),
        ExerciseOption(
            id = 41, name = "杠铃深蹲", mainPart = TrainingTarget.LEG,
            intro = "杠铃置于上背，双脚约肩宽站立。", equipment = "杠铃",
            steps = listOf("杠铃置于上背，双脚约肩宽站立。", "屈髋屈膝下蹲至合适深度，再用脚掌发力站起。", "膝盖方向与脚尖一致，躯干保持稳定。"),
            cautions = listOf("不要膝盖内扣。", "不要圆背。", "大重量使用安全杆。"),
            primaryMuscles = listOf(MuscleRegion.QUADRICEPS, MuscleRegion.GLUTES),
            secondaryMuscles = listOf(MuscleRegion.HAMSTRINGS, MuscleRegion.ABS, MuscleRegion.LOWER_BACK),
            recordingType = RecordingType.STRENGTH,
        ),
        ExerciseOption(
            id = 42, name = "前蹲", mainPart = TrainingTarget.LEG,
            intro = "杠铃放在前三角和锁骨附近，肘部抬高。", equipment = "杠铃",
            steps = listOf("杠铃放在前三角和锁骨附近，肘部抬高。", "保持躯干更直立地下蹲，再站起。", "核心和上背收紧，避免杠铃滚落。"),
            cautions = listOf("手腕不适可用交叉握。", "不要肘部下掉。", "重量从轻开始适应。"),
            primaryMuscles = listOf(MuscleRegion.QUADRICEPS),
            secondaryMuscles = listOf(MuscleRegion.GLUTES, MuscleRegion.ABS, MuscleRegion.UPPER_BACK),
            recordingType = RecordingType.STRENGTH,
        ),
        ExerciseOption(
            id = 43, name = "高脚杯深蹲", mainPart = TrainingTarget.LEG,
            intro = "双手抱住哑铃或壶铃于胸前。", equipment = "哑铃",
            steps = listOf("双手抱住哑铃或壶铃于胸前。", "下蹲时肘部可自然向膝内侧方向。", "保持胸口打开，脚掌稳定发力站起。"),
            cautions = listOf("不要塌腰。", "膝盖跟随脚尖。", "适合作为深蹲学习动作。"),
            primaryMuscles = listOf(MuscleRegion.QUADRICEPS, MuscleRegion.GLUTES),
            secondaryMuscles = listOf(MuscleRegion.ABS, MuscleRegion.ADDUCTORS),
            recordingType = RecordingType.STRENGTH,
        ),
        ExerciseOption(
            id = 44, name = "腿举", mainPart = TrainingTarget.LEG,
            intro = "坐进腿举机，双脚踩在踏板上约肩宽。", equipment = "腿举机",
            steps = listOf("坐进腿举机，双脚踩在踏板上约肩宽。", "解除安全锁，弯膝下降至可控深度后推回。", "全程保持腰背贴住靠垫。"),
            cautions = listOf("不要膝盖内扣。", "不要在顶端锁死膝盖。", "不要下降到骨盆后翻。"),
            primaryMuscles = listOf(MuscleRegion.QUADRICEPS, MuscleRegion.GLUTES),
            secondaryMuscles = listOf(MuscleRegion.HAMSTRINGS, MuscleRegion.CALVES),
            recordingType = RecordingType.STRENGTH,
        ),
        ExerciseOption(
            id = 45, name = "行走弓步", mainPart = TrainingTarget.LEG,
            intro = "站立后向前迈出一步，身体保持直立。", equipment = "自重",
            steps = listOf("站立后向前迈出一步，身体保持直立。", "下降至前腿发力明显，再推起并迈下一步。", "保持膝盖与脚尖方向一致。"),
            cautions = listOf("不要前膝明显内扣。", "步幅过小会增加膝压力。", "保持核心稳定。"),
            primaryMuscles = listOf(MuscleRegion.QUADRICEPS, MuscleRegion.GLUTES),
            secondaryMuscles = listOf(MuscleRegion.HAMSTRINGS, MuscleRegion.ABS, MuscleRegion.CALVES),
            recordingType = RecordingType.BODYWEIGHT,
        ),
        ExerciseOption(
            id = 46, name = "保加利亚分腿蹲", mainPart = TrainingTarget.LEG,
            intro = "后脚放在凳上，前脚站稳。", equipment = "哑铃",
            steps = listOf("后脚放在凳上，前脚站稳。", "屈膝下降至前腿发力，再站起。", "身体可略前倾以增强臀部参与。"),
            cautions = listOf("不要前膝内扣。", "前脚距离不合适会影响平衡。", "左右两侧保持同等训练量。"),
            primaryMuscles = listOf(MuscleRegion.QUADRICEPS, MuscleRegion.GLUTES),
            secondaryMuscles = listOf(MuscleRegion.HAMSTRINGS, MuscleRegion.ABS),
            recordingType = RecordingType.STRENGTH,
        ),
        ExerciseOption(
            id = 47, name = "坐姿腿屈伸", mainPart = TrainingTarget.LEG,
            intro = "调整坐垫和脚垫，使膝轴与机器轴接近。", equipment = "器械",
            steps = listOf("调整坐垫和脚垫，使膝轴与机器轴接近。", "伸直膝盖将脚垫抬起，顶端短暂停顿。", "慢速下放，保持股四头肌张力。"),
            cautions = listOf("不要猛甩小腿。", "膝不适时减少重量和幅度。", "避免完全靠惯性。"),
            primaryMuscles = listOf(MuscleRegion.QUADRICEPS),
            secondaryMuscles = listOf(MuscleRegion.QUADRICEPS),
            recordingType = RecordingType.STRENGTH,
        ),
        ExerciseOption(
            id = 48, name = "俯卧/坐姿腿弯举", mainPart = TrainingTarget.LEG,
            intro = "调整机器，使膝关节轴线与机器轴接近。", equipment = "器械",
            steps = listOf("调整机器，使膝关节轴线与机器轴接近。", "屈膝将脚垫向臀部方向卷起。", "顶端收缩后慢速放回。"),
            cautions = listOf("不要抬臀借力。", "不要让重量片碰撞。", "膝后侧不适时减小幅度。"),
            primaryMuscles = listOf(MuscleRegion.HAMSTRINGS),
            secondaryMuscles = listOf(MuscleRegion.CALVES),
            recordingType = RecordingType.STRENGTH,
        ),
        ExerciseOption(
            id = 49, name = "罗马尼亚硬拉", mainPart = TrainingTarget.LEG,
            intro = "站立持杠或哑铃，膝盖微屈。", equipment = "杠铃",
            steps = listOf("站立持杠或哑铃，膝盖微屈。", "髋部向后推，重量沿腿前侧下降。", "感到腘绳肌拉伸后用臀腿发力回到站立。"),
            cautions = listOf("不要圆背。", "重量不要远离身体。", "不是下蹲动作，膝角保持相对稳定。"),
            primaryMuscles = listOf(MuscleRegion.HAMSTRINGS, MuscleRegion.GLUTES),
            secondaryMuscles = listOf(MuscleRegion.LOWER_BACK, MuscleRegion.UPPER_BACK, MuscleRegion.FOREARM),
            recordingType = RecordingType.STRENGTH,
        ),
        ExerciseOption(
            id = 50, name = "臀推", mainPart = TrainingTarget.GLUTE,
            intro = "上背靠凳，杠铃置于髋部并加软垫。", equipment = "杠铃",
            steps = listOf("上背靠凳，杠铃置于髋部并加软垫。", "脚掌踩稳，向上伸髋至身体接近平直。", "顶端收紧臀部，慢速下放。"),
            cautions = listOf("不要腰椎过度反弓。", "脚离身体太远会更多用腘绳肌。", "保持下巴微收。"),
            primaryMuscles = listOf(MuscleRegion.GLUTES),
            secondaryMuscles = listOf(MuscleRegion.HAMSTRINGS, MuscleRegion.QUADRICEPS),
            recordingType = RecordingType.STRENGTH,
        ),
        ExerciseOption(
            id = 51, name = "臀桥", mainPart = TrainingTarget.GLUTE,
            intro = "仰卧屈膝，脚跟靠近臀部。", equipment = "自重",
            steps = listOf("仰卧屈膝，脚跟靠近臀部。", "用臀部发力将髋部抬起。", "顶端短暂停顿，慢速回到地面。"),
            cautions = listOf("不要用腰顶起。", "膝盖不要内扣。", "可加弹力带增强臀中肌参与。"),
            primaryMuscles = listOf(MuscleRegion.GLUTES),
            secondaryMuscles = listOf(MuscleRegion.HAMSTRINGS, MuscleRegion.ABS),
            recordingType = RecordingType.BODYWEIGHT,
        ),
        ExerciseOption(
            id = 52, name = "站姿提踵", mainPart = TrainingTarget.LEG,
            intro = "前脚掌踩在踏板或台阶上，脚跟可下沉。", equipment = "器械",
            steps = listOf("前脚掌踩在踏板或台阶上，脚跟可下沉。", "向上踮脚至小腿收缩，再慢速下降。", "底部感受小腿拉伸，顶端停顿。"),
            cautions = listOf("不要用膝盖弹动。", "幅度不要过小。", "保持踝关节稳定。"),
            primaryMuscles = listOf(MuscleRegion.CALVES),
            secondaryMuscles = listOf(MuscleRegion.CALVES),
            recordingType = RecordingType.STRENGTH,
        ),
        ExerciseOption(
            id = 53, name = "坐姿提踵", mainPart = TrainingTarget.LEG,
            intro = "坐在器械上，膝盖弯曲，前脚掌踩踏板。", equipment = "器械",
            steps = listOf("坐在器械上，膝盖弯曲，前脚掌踩踏板。", "向上踮脚抬起重量，再慢速下降。", "保持底部拉伸和顶端收缩。"),
            cautions = listOf("不要借身体晃动。", "踝部不适时减小重量。", "动作节奏要稳定。"),
            primaryMuscles = listOf(MuscleRegion.CALVES),
            secondaryMuscles = listOf(MuscleRegion.CALVES),
            recordingType = RecordingType.STRENGTH,
        ),
        ExerciseOption(
            id = 54, name = "登阶", mainPart = TrainingTarget.LEG,
            intro = "一脚踩上箱子或踏台，身体保持直立。", equipment = "箱子",
            steps = listOf("一脚踩上箱子或踏台，身体保持直立。", "用上方腿发力站上平台。", "控制下放回地面，左右交替或单侧完成。"),
            cautions = listOf("不要用后脚大力蹬地。", "膝盖不要内扣。", "箱子高度以动作可控为准。"),
            primaryMuscles = listOf(MuscleRegion.QUADRICEPS, MuscleRegion.GLUTES),
            secondaryMuscles = listOf(MuscleRegion.HAMSTRINGS, MuscleRegion.CALVES, MuscleRegion.ABS),
            recordingType = RecordingType.STRENGTH,
        ),
        ExerciseOption(
            id = 55, name = "哈克深蹲", mainPart = TrainingTarget.LEG,
            intro = "背部贴靠垫，肩部置于垫下，双脚踩稳。", equipment = "哈克深蹲机",
            steps = listOf("背部贴靠垫，肩部置于垫下，双脚踩稳。", "屈膝下降至可控深度，再推回。", "脚位较低更偏股四头，较高更偏臀腿。"),
            cautions = listOf("不要膝盖内扣。", "不要在顶端锁死膝盖。", "下放速度要控制。"),
            primaryMuscles = listOf(MuscleRegion.QUADRICEPS),
            secondaryMuscles = listOf(MuscleRegion.GLUTES, MuscleRegion.HAMSTRINGS),
            recordingType = RecordingType.STRENGTH,
        ),
        ExerciseOption(
            id = 56, name = "绳索后踢腿", mainPart = TrainingTarget.GLUTE,
            intro = "脚踝绑低位绳索，身体略前倾扶稳。", equipment = "绳索",
            steps = listOf("脚踝绑低位绳索，身体略前倾扶稳。", "保持膝微屈，将腿向后上方伸展。", "顶端收缩臀部，慢速回放。"),
            cautions = listOf("不要腰部反弓借力。", "动作幅度不必过高。", "骨盆保持稳定。"),
            primaryMuscles = listOf(MuscleRegion.GLUTES),
            secondaryMuscles = listOf(MuscleRegion.HAMSTRINGS, MuscleRegion.ABS),
            recordingType = RecordingType.STRENGTH,
        ),
        ExerciseOption(
            id = 57, name = "平板支撑", mainPart = TrainingTarget.ABS,
            intro = "前臂撑地，肘在肩下方，双脚向后伸直。", equipment = "自重",
            steps = listOf("前臂撑地，肘在肩下方，双脚向后伸直。", "收紧腹部和臀部，保持身体一条直线。", "均匀呼吸，不要憋气。"),
            cautions = listOf("不要塌腰。", "不要抬臀过高。", "腰痛时缩短时间。"),
            primaryMuscles = listOf(MuscleRegion.ABS),
            secondaryMuscles = listOf(MuscleRegion.GLUTES, MuscleRegion.DELTOIDS),
            recordingType = RecordingType.TIMED,
        ),
        ExerciseOption(
            id = 58, name = "侧平板支撑", mainPart = TrainingTarget.ABS,
            intro = "侧卧用前臂撑地，双脚叠放或前后错开。", equipment = "自重",
            steps = listOf("侧卧用前臂撑地，双脚叠放或前后错开。", "抬起髋部，让身体成一直线。", "保持骨盆不向前后旋转。"),
            cautions = listOf("肩不适时缩短时间。", "不要让髋部下沉。", "左右两侧都训练。"),
            primaryMuscles = listOf(MuscleRegion.OBLIQUES),
            secondaryMuscles = listOf(MuscleRegion.GLUTES, MuscleRegion.DELTOIDS),
            recordingType = RecordingType.TIMED,
        ),
        ExerciseOption(
            id = 59, name = "死虫", mainPart = TrainingTarget.ABS,
            intro = "仰卧抬起双臂和双腿，腰背轻贴地面。", equipment = "自重",
            steps = listOf("仰卧抬起双臂和双腿，腰背轻贴地面。", "对侧手脚缓慢向远处伸展，再回到起始位置。", "保持核心收紧，腰不要离地。"),
            cautions = listOf("动作宁慢不快。", "不要用惯性摆腿。", "腰部不适时缩小幅度。"),
            primaryMuscles = listOf(MuscleRegion.ABS),
            secondaryMuscles = listOf(MuscleRegion.QUADRICEPS, MuscleRegion.DELTOIDS),
            recordingType = RecordingType.BODYWEIGHT,
        ),
        ExerciseOption(
            id = 60, name = "悬垂举腿", mainPart = TrainingTarget.ABS,
            intro = "双手悬垂，肩胛保持稳定。", equipment = "单杠",
            steps = listOf("双手悬垂，肩胛保持稳定。", "抬腿至髋部屈曲明显，可进一步卷骨盆。", "慢速下放，避免身体摆动。"),
            cautions = listOf("不要甩腿借力。", "握力不足可用护腕。", "腰部不适时改屈膝版本。"),
            primaryMuscles = listOf(MuscleRegion.ABS),
            secondaryMuscles = listOf(MuscleRegion.QUADRICEPS, MuscleRegion.FOREARM),
            recordingType = RecordingType.STRENGTH,
        ),
        ExerciseOption(
            id = 61, name = "绳索卷腹", mainPart = TrainingTarget.ABS,
            intro = "跪在高位绳索前，双手握绳靠近头部。", equipment = "绳索",
            steps = listOf("跪在高位绳索前，双手握绳靠近头部。", "收缩腹部让胸骨向骨盆方向卷曲。", "慢速回到起始，保持髋部相对稳定。"),
            cautions = listOf("不要用手臂拉绳。", "不要坐髋后移太多。", "腰痛者谨慎。"),
            primaryMuscles = listOf(MuscleRegion.ABS),
            secondaryMuscles = listOf(MuscleRegion.OBLIQUES),
            recordingType = RecordingType.STRENGTH,
        ),
        ExerciseOption(
            id = 62, name = "俄罗斯转体", mainPart = TrainingTarget.ABS,
            intro = "坐姿微后仰，双脚可踩地或抬起。", equipment = "自重",
            steps = listOf("坐姿微后仰，双脚可踩地或抬起。", "双手持重或空手，躯干左右旋转。", "保持核心收紧，动作可控。"),
            cautions = listOf("不要只甩手臂。", "腰不适时减小幅度。", "重量不宜过大。"),
            primaryMuscles = listOf(MuscleRegion.OBLIQUES),
            secondaryMuscles = listOf(MuscleRegion.ABS, MuscleRegion.QUADRICEPS),
            recordingType = RecordingType.BODYWEIGHT,
        ),
        ExerciseOption(
            id = 63, name = "健腹轮", mainPart = TrainingTarget.ABS,
            intro = "跪姿握住健腹轮，核心和臀部收紧。", equipment = "健腹轮",
            steps = listOf("跪姿握住健腹轮，核心和臀部收紧。", "缓慢向前推出身体，保持腰背稳定。", "用腹部力量将身体拉回起始位置。"),
            cautions = listOf("不要塌腰。", "推出距离量力而行。", "初学者先做短幅度。"),
            primaryMuscles = listOf(MuscleRegion.ABS),
            secondaryMuscles = listOf(MuscleRegion.UPPER_BACK, MuscleRegion.DELTOIDS),
            recordingType = RecordingType.STRENGTH,
        ),
        ExerciseOption(
            id = 64, name = "自行车卷腹", mainPart = TrainingTarget.ABS,
            intro = "仰卧双手轻扶头侧，双腿抬起。", equipment = "自重",
            steps = listOf("仰卧双手轻扶头侧，双腿抬起。", "对侧肘膝靠近，同时另一腿伸展。", "左右交替，保持腹部发力。"),
            cautions = listOf("不要用手拉脖子。", "动作不要过快。", "腰部不适时减少伸腿幅度。"),
            primaryMuscles = listOf(MuscleRegion.ABS, MuscleRegion.OBLIQUES),
            secondaryMuscles = listOf(MuscleRegion.QUADRICEPS),
            recordingType = RecordingType.BODYWEIGHT,
        ),
        ExerciseOption(
            id = 65, name = "帕洛夫抗旋转推", mainPart = TrainingTarget.ABS,
            intro = "侧身站在绳索或弹力带旁，双手握把于胸前。", equipment = "绳索",
            steps = listOf("侧身站在绳索或弹力带旁，双手握把于胸前。", "向前推出手臂，抵抗身体被拉向一侧。", "保持骨盆和胸口朝前，慢速收回。"),
            cautions = listOf("不要让身体旋转。", "重量以能稳定控制为准。", "左右两侧都做。"),
            primaryMuscles = listOf(MuscleRegion.ABS, MuscleRegion.OBLIQUES),
            secondaryMuscles = listOf(MuscleRegion.GLUTES, MuscleRegion.DELTOIDS),
            recordingType = RecordingType.STRENGTH,
        ),
        ExerciseOption(
            id = 66, name = "跑步机跑步", mainPart = TrainingTarget.CARDIO,
            intro = "选择合适速度，先用慢跑或快走热身。", equipment = "跑步机",
            steps = listOf("选择合适速度，先用慢跑或快走热身。", "保持上身放松，脚步节奏稳定。", "训练结束逐渐降速冷身。"),
            cautions = listOf("不要一开始速度过快。", "鞋带和跑带安全夹要检查。", "膝踝不适时降低速度或坡度。"),
            primaryMuscles = emptyList(),
            secondaryMuscles = listOf(MuscleRegion.CALVES, MuscleRegion.QUADRICEPS, MuscleRegion.GLUTES, MuscleRegion.ABS),
            recordingType = RecordingType.CARDIO,
        ),
        ExerciseOption(
            id = 67, name = "坡度快走", mainPart = TrainingTarget.CARDIO,
            intro = "设置中低速度和合适坡度。", equipment = "跑步机",
            steps = listOf("设置中低速度和合适坡度。", "身体保持自然直立，手臂轻松摆动。", "用稳定步频完成训练，不要抓扶手借力。"),
            cautions = listOf("坡度过高会增加小腿和腰部压力。", "不要身体后仰。", "逐渐增加时间和坡度。"),
            primaryMuscles = emptyList(),
            secondaryMuscles = listOf(MuscleRegion.GLUTES, MuscleRegion.HAMSTRINGS, MuscleRegion.CALVES),
            recordingType = RecordingType.CARDIO,
        ),
        ExerciseOption(
            id = 68, name = "动感单车/骑行", mainPart = TrainingTarget.CARDIO,
            intro = "调整座椅高度，使膝盖在底部仍微屈。", equipment = "单车",
            steps = listOf("调整座椅高度，使膝盖在底部仍微屈。", "保持稳定踩踏节奏，根据目标调节阻力。", "训练结束降低阻力慢踩冷身。"),
            cautions = listOf("不要座椅过低导致膝压力。", "膝盖保持朝前。", "避免上身过度晃动。"),
            primaryMuscles = emptyList(),
            secondaryMuscles = listOf(MuscleRegion.QUADRICEPS, MuscleRegion.GLUTES, MuscleRegion.CALVES),
            recordingType = RecordingType.CARDIO,
        ),
        ExerciseOption(
            id = 69, name = "划船机", mainPart = TrainingTarget.CARDIO,
            intro = "脚固定好，先用腿发力，再髋部后摆，最后拉手柄。", equipment = "划船机",
            steps = listOf("脚固定好，先用腿发力，再髋部后摆，最后拉手柄。", "回程按手臂、髋、腿的顺序恢复。", "保持背部中立，节奏连贯。"),
            cautions = listOf("不要一开始就用手臂硬拉。", "不要圆背。", "阻力不必调到最高。"),
            primaryMuscles = emptyList(),
            secondaryMuscles = listOf(MuscleRegion.UPPER_BACK, MuscleRegion.GLUTES),
            recordingType = RecordingType.CARDIO,
        ),
        ExerciseOption(
            id = 70, name = "椭圆机", mainPart = TrainingTarget.CARDIO,
            intro = "双脚踩稳踏板，双手握住扶手或保持自然摆臂。", equipment = "椭圆机",
            steps = listOf("双脚踩稳踏板，双手握住扶手或保持自然摆臂。", "以稳定节奏推动踏板，保持呼吸。", "根据状态调整阻力和坡度。"),
            cautions = listOf("不要身体左右晃动过大。", "膝盖朝脚尖方向。", "初次使用从低阻力开始。"),
            primaryMuscles = emptyList(),
            secondaryMuscles = listOf(MuscleRegion.GLUTES, MuscleRegion.DELTOIDS, MuscleRegion.UPPER_BACK),
            recordingType = RecordingType.CARDIO,
        ),
        ExerciseOption(
            id = 71, name = "跳绳", mainPart = TrainingTarget.CARDIO,
            intro = "选择合适绳长，身体直立，手腕轻微转绳。", equipment = "跳绳",
            steps = listOf("选择合适绳长，身体直立，手腕轻微转绳。", "用前脚掌小幅弹跳，保持节奏。", "分组完成，逐渐延长连续时间。"),
            cautions = listOf("不要跳得过高。", "膝踝不适时减少量。", "地面过硬时注意缓冲。"),
            primaryMuscles = emptyList(),
            secondaryMuscles = listOf(MuscleRegion.CALVES, MuscleRegion.DELTOIDS, MuscleRegion.ABS),
            recordingType = RecordingType.CARDIO,
        ),
        ExerciseOption(
            id = 72, name = "战绳", mainPart = TrainingTarget.CARDIO,
            intro = "双脚站稳，双手握住战绳末端。", equipment = "战绳",
            steps = listOf("双脚站稳，双手握住战绳末端。", "快速交替或同时甩绳，保持核心稳定。", "按时间分组完成，组间短休。"),
            cautions = listOf("不要耸肩过度。", "腰背保持稳定。", "手腕不适时降低强度。"),
            primaryMuscles = emptyList(),
            secondaryMuscles = listOf(MuscleRegion.DELTOIDS, MuscleRegion.ABS, MuscleRegion.UPPER_BACK),
            recordingType = RecordingType.CARDIO,
        ),
        ExerciseOption(
            id = 73, name = "波比跳", mainPart = TrainingTarget.CARDIO,
            intro = "站立后下蹲，双手撑地，双脚向后跳成俯撑。", equipment = "自重",
            steps = listOf("站立后下蹲，双手撑地，双脚向后跳成俯撑。", "可完成俯卧撑，再收腿跳起。", "保持节奏，动作完整但不过度追求速度。"),
            cautions = listOf("疲劳时动作容易塌腰。", "膝踝不适时去掉跳跃。", "心肺压力大，循序渐进。"),
            primaryMuscles = emptyList(),
            secondaryMuscles = listOf(MuscleRegion.CHEST, MuscleRegion.DELTOIDS, MuscleRegion.ABS),
            recordingType = RecordingType.CARDIO,
        ),
        ExerciseOption(
            id = 74, name = "开合跳", mainPart = TrainingTarget.CARDIO,
            intro = "站立开始，双脚向两侧跳开，同时双臂上举。", equipment = "自重",
            steps = listOf("站立开始，双脚向两侧跳开，同时双臂上举。", "再跳回双脚并拢，手臂回到身体两侧。", "保持轻盈落地和稳定节奏。"),
            cautions = listOf("膝踝不适时改低冲击版本。", "不要耸肩。", "地面要防滑。"),
            primaryMuscles = emptyList(),
            secondaryMuscles = listOf(MuscleRegion.CALVES, MuscleRegion.DELTOIDS, MuscleRegion.GLUTES),
            recordingType = RecordingType.CARDIO,
        ),
        ExerciseOption(
            id = 75, name = "登阶机", mainPart = TrainingTarget.CARDIO,
            intro = "双脚踩稳台阶，身体自然直立。", equipment = "登阶机",
            steps = listOf("双脚踩稳台阶，身体自然直立。", "以稳定节奏持续踏步。", "可轻扶把手保持平衡，但不要把体重压在手上。"),
            cautions = listOf("不要弯腰趴扶手。", "膝盖跟随脚尖。", "初学者从低速度开始。"),
            primaryMuscles = emptyList(),
            secondaryMuscles = listOf(MuscleRegion.GLUTES, MuscleRegion.QUADRICEPS, MuscleRegion.CALVES),
            recordingType = RecordingType.CARDIO,
        ),
        ExerciseOption(
            id = 76, name = "Y字侧平举", mainPart = TrainingTarget.SHOULDER,
            intro = "双手持轻重量，从身体前下方向斜上方抬起，手臂形成Y字。", equipment = "哑铃/绳索",
            steps = listOf("双手持轻重量，从身体前下方向斜上方抬起，手臂形成Y字。", "保持肘部微屈，沿肩胛平面抬至耳侧或略低位置。", "顶端短暂停顿，控制重量沿原路径缓慢下放。"),
            cautions = listOf("不要耸肩或用斜方肌抢力。", "重量宜轻，避免腰部后仰借力。", "肩部出现夹挤或疼痛时减小幅度。"),
            primaryMuscles = listOf(MuscleRegion.DELTOIDS),
            secondaryMuscles = listOf(MuscleRegion.TRAPEZIUS, MuscleRegion.UPPER_BACK),
            recordingType = RecordingType.STRENGTH,
        ),
        ExerciseOption(
            id = 77, name = "单手钢线下拉", mainPart = TrainingTarget.BACK,
            intro = "单手握住高位钢线把手，躯干保持稳定，肩胛先向下沉。", equipment = "龙门架",
            steps = listOf("单手握住高位钢线把手，躯干保持稳定，肩胛先向下沉。", "沿身体侧前方将肘部拉向髋部，感受背阔肌收缩。", "缓慢伸展手臂并让肩胛上旋，完成充分但可控的回放。"),
            cautions = listOf("不要大幅侧屈或旋转躯干借力。", "避免耸肩后直接用肱二头肌拉动。", "左右两侧使用相同重量和训练量。"),
            primaryMuscles = listOf(MuscleRegion.UPPER_BACK),
            secondaryMuscles = listOf(MuscleRegion.BICEPS, MuscleRegion.FOREARM),
            recordingType = RecordingType.STRENGTH,
        ),
        ExerciseOption(
            id = 78, name = "对握下拉", mainPart = TrainingTarget.BACK,
            intro = "坐稳并固定大腿，双手以掌心相对的中立握法握住把手。", equipment = "高位下拉器",
            steps = listOf("坐稳并固定大腿，双手以掌心相对的中立握法握住把手。", "先下沉肩胛，再将把手拉向上胸，肘部沿身体两侧向下。", "保持胸口打开，控制把手回到手臂充分伸展的位置。"),
            cautions = listOf("不要用过度后仰把动作变成划船。", "不要让肩膀在回放末端突然松垮。", "腕肘不适时调整握距或把手类型。"),
            primaryMuscles = listOf(MuscleRegion.UPPER_BACK),
            secondaryMuscles = listOf(MuscleRegion.BICEPS, MuscleRegion.TRAPEZIUS, MuscleRegion.FOREARM),
            recordingType = RecordingType.STRENGTH,
        ),
        ExerciseOption(
            id = 79, name = "单手器械划船", mainPart = TrainingTarget.BACK,
            intro = "调整座椅和胸垫，单手握住把手，胸部稳定贴靠。", equipment = "划船器械",
            steps = listOf("调整座椅和胸垫，单手握住把手，胸部稳定贴靠。", "用肘部带动把手向髋部或肋骨方向拉，肩胛向后下方收紧。", "保持躯干不旋转，缓慢前送手臂至背部充分拉伸。"),
            cautions = listOf("不要扭转身体完成末端幅度。", "避免耸肩或用手臂抢先发力。", "座椅高度应让拉动路径自然且肩部舒适。"),
            primaryMuscles = listOf(MuscleRegion.UPPER_BACK),
            secondaryMuscles = listOf(MuscleRegion.BICEPS, MuscleRegion.DELTOIDS, MuscleRegion.TRAPEZIUS),
            recordingType = RecordingType.STRENGTH,
        ),
        ExerciseOption(
            id = 80, name = "坐姿开肘划船", mainPart = TrainingTarget.BACK,
            intro = "坐稳握住绳索或器械把手，手肘向身体两侧打开。", equipment = "绳索/器械",
            steps = listOf("坐稳握住绳索或器械把手，手肘向身体两侧打开。", "将把手拉向上腹或胸下方，同时主动后收肩胛。", "顶端保持上臂接近肩线，控制回放并让上背充分伸展。"),
            cautions = listOf("不要耸肩把负荷转移到上斜方肌。", "避免腰部大幅前后摆动借力。", "肩前侧不适时降低开肘角度。"),
            primaryMuscles = listOf(MuscleRegion.UPPER_BACK, MuscleRegion.DELTOIDS),
            secondaryMuscles = listOf(MuscleRegion.TRAPEZIUS, MuscleRegion.BICEPS),
            recordingType = RecordingType.STRENGTH,
        ),
        ExerciseOption(
            id = 81, name = "单腿硬拉", mainPart = TrainingTarget.LEG,
            intro = "单脚站稳，支撑腿膝盖微屈，双手持哑铃或徒手保持平衡。", equipment = "哑铃",
            steps = listOf("单脚站稳，支撑腿膝盖微屈，双手持哑铃或徒手保持平衡。", "髋部向后推，非支撑腿向后伸，躯干与后腿同步前倾。", "保持骨盆朝向地面，用支撑腿臀部和腘绳肌发力站回。"),
            cautions = listOf("不要圆背或让骨盆向外翻开。", "先掌握平衡和髋铰链，再增加重量。", "左右两侧保持相同训练量。"),
            primaryMuscles = listOf(MuscleRegion.HAMSTRINGS, MuscleRegion.GLUTES),
            secondaryMuscles = listOf(MuscleRegion.LOWER_BACK, MuscleRegion.ADDUCTORS, MuscleRegion.ABS),
            recordingType = RecordingType.STRENGTH,
        ),
        ExerciseOption(
            id = 82, name = "山羊挺身", mainPart = TrainingTarget.LEG,
            intro = "调整罗马椅垫板至髋部下方，双脚固定，身体保持中立。", equipment = "罗马椅",
            steps = listOf("调整罗马椅垫板至髋部下方，双脚固定，身体保持中立。", "以髋关节为轴控制上身下放，感受臀部和腘绳肌拉伸。", "收紧臀腿将身体抬回直线位置，顶端不要继续后仰。"),
            cautions = listOf("不要用腰椎快速甩动完成动作。", "顶端只回到身体成直线，避免过度反弓。", "腰部不适时缩小幅度并优先使用自重。"),
            primaryMuscles = listOf(MuscleRegion.GLUTES, MuscleRegion.HAMSTRINGS),
            secondaryMuscles = listOf(MuscleRegion.LOWER_BACK),
            recordingType = RecordingType.STRENGTH,
        ),
    )
}

